### ISSUE TITLE
Permanent burn doesn't persist through scene transition

### ISSUE THREAD

**Issue by reseune** [DigitalzombieTLD/Candlelight#10]
Hey!

I am having the same issue as the one I reported with Infinite Fires: when I change from interior to exterior scenes, my candles go out, even though I have them set to "Permanent" in the mod settings. I am happy to help diagnose this or do whatever you need if you have the time to take a look at this. 

Thanks!

**Comment by reseune** [comment]
This issue appears to have been resolved with one of the updates. Thank you!

**Comment by JesseWV** [comment]
Have the same issue on latest version 1.4.0
