### ISSUE TITLE
extra config options?

### ISSUE THREAD

**Issue by SquareBall789** [DigitalzombieTLD/Candlelight#4]
Would it be possible to add config options for candle recipe cost and/or an option to change burn time?

**Comment by DigitalzombieTLD** [comment]
![wellyes](https://user-images.githubusercontent.com/67791610/159273803-d9431775-ac7d-431e-8fcb-7b152e1fec7c.jpg)
Meaning: It's possible, but I don't want to do it ;)

But (!!!) you can do it yourself :) 

You can extract the "**candlelight.modcomponent**" file. It's just a renamed zip. Inside you find the subfolder "**auto-mapped**". In the "**candle.json**" you can increase MaxHP for burn duration. The candles use the item condition and NOT the normal "duration" or "burn time" you encounter in the files.

The folder "**blueprints**" got the recipes for crafting. There you can change what items (and how much of them) are needed.

**Comment by SquareBall789** [comment]
Yeah that's fair enough, I had previously tried messing around with the dll trying to edit the mod but I forgot about the .modcomponent
